Step 1.-- After creating the DB. 

/oradata/database/SOCAN19 --> this is the path in which table spaces going to create

CREATE TABLESPACE TBS0 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/TBS0.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TBS1 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/TBS1.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TBS2 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/TBS2.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TBS3 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/TBS3.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TBS4 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/TBS4.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TBS5 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/TBS5.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TBS6 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/TBS6.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TBS7 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/TBS7.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TBS8 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/TBS8.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TBS9 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/TBS9.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE INDEX0 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/INDEX0.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE INDEX1 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/INDEX1.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE INDEX2 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/INDEX2.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE INDEX3 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/INDEX3.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE INDEX4 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/INDEX4.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE INDEX5 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/INDEX5.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE INDEX6 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/INDEX6.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE INDEX7 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/INDEX7.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE INDEX8 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/INDEX8.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE INDEX9 LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/INDEX9.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE INDEXTEMP LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/INDEXTEMP.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TBSTEMP LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/TBSTEMP.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE CDSLOB LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/CDSLOB.ora' SIZE 50M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE ORACLETMP LOGGING DATAFILE '/oradata/JDKTEST/JDKTEST/ORACLETMP.ora' SIZE 10M AUTOEXTEND ON NEXT  8k MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;


-----------------------------------------------------------
Step 2.-- To Create CDSWEB user in  DB. 

CREATE USER CDSWEB IDENTIFIED BY CDSWEB;
ALTER USER CDSWEB DEFAULT TABLESPACE TBS0 TEMPORARY TABLESPACE TEMP;
GRANT CONNECT ,RESOURCE TO CDSWEB;
grant Query Rewrite,create any view, Select_catalog_role to CDSWEB;
GRANT UNLIMITED TABLESPACE TO CDSWEB ;


CREATE USER DXO IDENTIFIED BY DXO;
ALTER USER DXO DEFAULT TABLESPACE TBS0 TEMPORARY TABLESPACE TEMP;
GRANT CONNECT ,RESOURCE TO DXO;
grant Query Rewrite,create any view, Select_catalog_role to DXO;
GRANT UNLIMITED TABLESPACE TO DXO ;


CREATE USER MOBILINK IDENTIFIED BY MOBILINK DEFAULT TABLESPACE TBS0;
GRANT CONNECT, RESOURCE TO MOBILINK;
GRANT QUERY REWRITE TO MOBILINK; 

CREATE USER PUSH IDENTIFIED BY PUSH;
ALTER USER PUSH DEFAULT TABLESPACE TBS0 TEMPORARY TABLESPACE TEMP;
GRANT CONNECT ,RESOURCE TO PUSH;
grant Query Rewrite,create any view, Select_catalog_role to PUSH;
GRANT UNLIMITED TABLESPACE TO PUSH ;




-- -for RGMAIN databases
/*
DROP ROLE level_0;

CREATE ROLE level_0 IDENTIFIED by sysc0nf;

GRANT connect TO level_0;
 -- -----------------
DROP ROLE level_1;

CREATE ROLE level_1 IDENTIFIED by sysc0nf;

GRANT connect TO level_1;
-- ---------------------------------
DROP ROLE level_2;

CREATE ROLE level_2 IDENTIFIED by sysc0nf;

GRANT CREATE SESSION TO level_2;
-- ----------------------------------
DROP ROLE level_3;

CREATE ROLE level_3 IDENTIFIED by sysc0nf;

GRANT DBA TO level_3;
*/

GRANT UNLIMITED TABLESPACE TO CDSWEB;

GRANT UNLIMITED TABLESPACE TO DXO;

Step 3.-- To Alter the System according the standard. 
-- ---------------------------------------------------------


--alter system set  SGA_MAX_SIZE=200M scope=spfile;
alter system set shared_pool_size =130m scope=spfile;
alter system set db_cache_size=32m scope=both;
alter system set SORT_AREA_SIZE=4194304 scope=spfile;
alter system set sort_area_retained_size=1048576 scope=spfile;
alter system set log_buffer=1048576 scope=spfile;
alter system set log_checkpoint_interval=1000000000;
alter system set log_checkpoint_timeout=0;
ALTER SYSTEM SET statistics_level=TYPICAL SCOPE=SPFILE;
alter system set java_pool_size=0 SCOPE=SPFILE;
alter system set large_pool_size=0 SCOPE=SPFILE;

-- The parameter to force log switch every hour is: 
-- alter system set archive_lag_target=900; 

alter system set cursor_sharing=force scope=spfile;
alter system set DB_CACHE_ADVICE = OFF;

-- Function based indexes
grant Query Rewrite,create any view, Select_catalog_role to CDSWEB;
--grant Query Rewrite,create any view, Select_catalog_role to DXO;
alter system set QUERY_REWRITE_INTEGRITY = TRUSTED scope=spfile;
alter system set QUERY_REWRITE_ENABLED = TRUE scope=spfile;
alter system set cursor_sharing=force scope=spfile;
alter system set CURSOR_SPACE_FOR_TIME=TRUE scope = spfile;

ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;


ALTER system SET SEC_CASE_SENSITIVE_LOGON=FALSE scope=both;

GRANT CREATE DATABASE LINK TO DXO;
GRANT CREATE ANY SEQUENCE TO DXO;
GRANT ALTER ANY SEQUENCE TO DXO;

GRANT CREATE DATABASE LINK TO CDSWEB;
GRANT CREATE ANY SEQUENCE TO CDSWEB;
GRANT ALTER ANY SEQUENCE TO CDSWEB;

GRANT CREATE DATABASE LINK TO PUSH;
GRANT CREATE ANY SEQUENCE TO PUSH;
GRANT ALTER ANY SEQUENCE TO PUSH;
=====================================
**Now blank DB is created and USER is created so we have to add database objects(DDL's)
  means execute latest DDLs files on DB via putty one by one in definite order/manner